"""Build docs/rules-review.xlsx — every codec rule with a blank column for Scott's corrections.

For rules NOT at 100%, the 'My uncertainty' column gives a long-form explanation:
  - what the codec currently emits
  - what Detailer actually does (with corpus evidence)
  - my hypothesis for why
  - the specific question/correction Scott can answer
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# Long-form explanations for the rules that aren't 100%.
LONG = {
    5: (
        "WHAT WE EMIT: An InnerService hole at exactly 296mm from the BOTTOM of every wall stud (S/J), but only when the plan is LBW or NLBW and the stud is at least 500mm long. Position is fixed.\n\n"
        "WHAT DETAILER DOES: Detailer emits InnerService holes on wall studs at this height too — but it is SELECTIVE. It only puts the hole on SOME of the studs, not all. When we emit on every stud, we generate dozens of extra holes Detailer didn't put there.\n\n"
        "MY HYPOTHESIS: Detailer is reading something from project metadata that we don't import — most likely electrical layout data (which studs are next to outlets, switches, light fittings). Or it's picking studs based on a fixed counting pattern (every 3rd stud, or only studs adjacent to openings).\n\n"
        "WHAT I NEED FROM YOU: How does Detailer (or your standard practice) decide WHICH studs get the 296mm hole? Is it (a) every Nth stud, (b) only studs next to a door/window, (c) only studs at electrical fitting positions read from a separate file, (d) all studs in some plans but not others, or (e) some other rule? If you can write the rule out, I'll match it."
    ),
    6: (
        "WHAT WE EMIT: An InnerService hole at exactly 446mm from the BOTTOM of every wall stud, paired with the 296mm hole. Same gates as rule #5.\n\n"
        "WHAT DETAILER DOES: Same selective behaviour as #5 — Detailer pairs the 446mm hole with the 296mm hole on the studs that get them.\n\n"
        "WHAT I NEED FROM YOU: Same answer as #5. Once I know which studs get the 296mm hole, I'll pair the 446mm one with it. ALSO: are these always 296 + 446, or do those two heights ever change (e.g. for taller walls, or for non-domestic occupancies)?"
    ),
    7: (
        "WHAT WE EMIT: A series of evenly-spaced web holes along the body of every wall stud, generated by framecad-import.ts post-processing. The number and spacing constants are hand-tuned and not derived from a HYTEK rule.\n\n"
        "WHAT DETAILER DOES: Web holes appear at specific positions in Detailer's output, but I haven't characterised the pattern across the corpus.\n\n"
        "WHAT I NEED FROM YOU: For a 2400mm wall stud, what web holes does Detailer emit (positions in mm from the bottom)? Is it (a) fixed positions, (b) evenly-spaced with a max-gap rule, (c) a fixed first hole + then evenly down, or (d) something else? Same question for a 2700mm stud and a 1800mm short-wall stud."
    ),
    8: (
        "WHAT WE EMIT: 89mm wall studs get exactly the same 4-op pattern as 70mm: Swage 0..39 + Dimple@16.5 at start, Swage end-39..end + Dimple@end-16.5 at the end. The 39mm and 16.5mm constants come from MACHINE_SETUPS['6'] (F325iT 89mm setup) which has Tab=35 + Clearance=4 = 39 — same as the 70mm setup.\n\n"
        "WHAT DETAILER DOES: In the one 89mm corpus we tested, this matches. But our 89mm sample is small.\n\n"
        "WHAT I NEED FROM YOU: Confirm or correct. Do 89mm wall studs really use the same 39mm Swage cap and 16.5mm dimple offset as 70mm? Or do they have a different cap span (e.g. wider because the profile is wider)? If different, what are the values?"
    ),
    12: (
        "WHAT WE EMIT: For king/cripple studs (Kb), the END Swage span isn't fixed — it scales with the stick's angle. Formula: span = 45 / cos(angle from horizontal). So a vertical Kb (90 deg from horizontal) gets 45mm. A 68.3 deg-from-horizontal Kb gets 121.6mm.\n\n"
        "WHAT DETAILER DOES: HG260001 PK4 LBW Kb1 at 68.3 deg has ref Swage 1354..1476.6 (span 122.6mm). Formula predicts 121.6 — match. We have one verified data point.\n\n"
        "MY HYPOTHESIS: The 45 isn't a HYTEK constant I can find. The 39 (standard tab + clearance) is documented. The 45 happens to fit the data on this one stick. The cos(angle) part is geometrically sensible — a perpendicular cap projected onto an angled stick axis grows by 1/cos(angle).\n\n"
        "WHAT I NEED FROM YOU: Is there a HYTEK or FrameCAD specification for cripple/king stud end caps? Specifically: (a) is the cap really angle-dependent, (b) is the perpendicular cap really 45mm (not 39mm like other sticks), and (c) what's the formal rule? If you have the cripple-stud detail in your construction standards, that's the answer."
    ),
    14: (
        "WHAT WE EMIT: 89mm cripple studs get the same Chamfer + Swage + Dimple pattern as 70mm Kb (rules #9-13), with the angle formula at the end.\n\n"
        "WHAT DETAILER DOES: Untested at scale on 89mm Kb sticks.\n\n"
        "WHAT I NEED FROM YOU: Same answer as #12 — but for 89mm cripple studs. Are the constants the same (45mm, 10mm), or different?"
    ),
    15: (
        "WHAT WE EMIT: When a stick is named H but matched as a 'cripple' (not full header), the end Swage span is 43mm (vs 39 for studs, 45 for Kb). Single sample.\n\n"
        "WHAT WORRIES ME: There are two different rule sets for sticks named H — one in CRIPPLE_ROLES (matches when role !== 'Kb') and one in HEADER_ROLES (matches when role === 'H'). Since H sticks always have role='H', HEADER_ROLES always wins, so this 43mm rule is probably DEAD CODE.\n\n"
        "WHAT I NEED FROM YOU: (a) Are there ever sticks named with H prefix that should be treated like cripple studs (43mm Swage cap) instead of full headers (39mm InnerNotch+LipNotch caps)? (b) If yes, what's the discriminator (length? Position in frame? A different role attribute)?"
    ),
    19: (
        "WHAT WE EMIT: On short top plates (T<200mm — these are sub-plates that sit ABOVE a header), we add a paired dimple at 58.5mm from the start. ONLY on LBW plans, not NLBW.\n\n"
        "WHAT DETAILER DOES: HG260001 PK4 LBW L4 (T2/T3/T4 sub-plates of length 121-127mm) shows ref dimples at 58.5. Our NLBW corpus doesn't show them.\n\n"
        "MY HYPOTHESIS: The 58.5 dimple is on a 70mm web — so 35mm (web/2) + 23.5mm = 58.5. Probably corresponds to a screw fixing or a strap location. The LBW-only gate suggests it's a load-bearing requirement that NLBW walls don't need.\n\n"
        "WHAT I NEED FROM YOU: (a) What does the 58.5mm dimple represent physically — strap fixing, header-to-plate connector, joist hanger? (b) Why does LBW need it but NLBW doesn't — is it the load path (LBW carries roof load down through the header, NLBW doesn't)? (c) Is the 58.5 always exactly that, or does it scale with profile or detail variant?"
    ),
    20: (
        "WHAT WE EMIT: Mirror of rule #19 at the end of the short T sub-plate (length-58.5).\n\n"
        "WHAT I NEED FROM YOU: Same answer as #19. The dimple appears at both ends symmetrically — once you tell me the rule for one end, the other follows."
    ),
    28: (
        "WHAT WE EMIT: Nothing — InnerNotch on long top plates is DELIBERATELY DISABLED. We tried emitting it and got 100 extras for only 12 matches.\n\n"
        "WHAT DETAILER DOES: SOME long T plates DO get InnerNotches in Detailer's output. We just haven't found the discriminator that separates the ones that should from the ones that shouldn't.\n\n"
        "MY HYPOTHESES: (a) Maybe only at king-stud crossings (not regular studs). (b) Maybe only on plates that span an opening (door/window). (c) Maybe only when the plate is paired with a header below. (d) Maybe related to the joint between two T-plate segments.\n\n"
        "WHAT I NEED FROM YOU: When does a long top plate get an InnerNotch in Detailer? What stud-intersection or geometric condition triggers it? If you can describe 'a long T gets InnerNotch when X', I'll add the rule."
    ),
    29: (
        "WHAT WE EMIT: Nothing — InnerService holes on top plates are DELIBERATELY DISABLED. Blind emission on PK1/PK2/PK4/PK5 produced 256 extras vs 14 missing.\n\n"
        "WHAT DETAILER DOES: A small fraction of T plates (~5%) get InnerService holes from Detailer. Most don't.\n\n"
        "MY HYPOTHESIS: Same as rules #5/#6 — Detailer is reading electrical-services data we don't import. Specific T plates that are designated for cable runs would get holes; standard ones wouldn't.\n\n"
        "WHAT I NEED FROM YOU: Same as #5/#6 — what tells Detailer to put service holes on a particular top plate? If it's external services data we don't have, that's a known limitation. If it's a derivable rule from XML we DO read (length? plan type? specific role like Tp vs T?), I can add it."
    ),
    30: (
        "WHAT WE EMIT: 89mm long top plates get the same 4-op pattern as 70mm (LipNotch caps + Dimple@16.5 each end).\n\n"
        "WHAT I NEED FROM YOU: Same as #8 — confirm 89mm uses the same 39mm cap and 16.5 dimple offset. Or correct the constants."
    ),
    32: (
        "WHAT WE EMIT: A Web hole at 8mm from the start of a 70mm bottom plate — but only when ALL THREE conditions are true: (a) the plate is 'primary' (named B1, OR any length >= 1500mm), (b) the plan name contains '-GF-' (ground floor), (c) the plan is LBW or NLBW (not RP/TIN/TB2B/CP).\n\n"
        "WHAT DETAILER DOES: This is what I observed across 4 corpora — but the rule was assembled by trial-and-error to suppress false emissions. Specifically: B-sub-plates (B2/B3/B4 above doors) DON'T get Web@8 even when on the ground floor; non-ground-floor walls (1F/2F) don't get them; truss/joist plans don't get them.\n\n"
        "MY HYPOTHESIS: This is the slab-anchor wiring access point — only the plate that actually sits ON the slab gets it. Sub-plates above doors aren't slab-touching so no need.\n\n"
        "WHAT I NEED FROM YOU: Confirm or correct: (a) is the rule really 'only the slab-bearing plate'? (b) is 'primary' (B1 or >=1500mm) the right detector? (c) is the 8mm offset correct (or is it dependent on the wall thickness, profile, or some other detail)? (d) any 89mm-specific differences?"
    ),
    34: (
        "WHAT WE EMIT: A Bolt at exactly 62mm from the start of a primary ground-floor B plate. Same gates as rule #32.\n\n"
        "WHAT WORRIES ME: 62mm isn't documented in the FrameCAD machine setup files. The setup field 'boltHoleToEnd' = 20 doesn't match. The 62mm constant has no setup-field source — it's empirical.\n\n"
        "MY HYPOTHESIS: 62mm is a HYTEK construction standard for slab anchor bolt position — close enough to the wall end for structural anchorage but far enough that the bolt doesn't conflict with the plate's end notch (which extends 39mm in).\n\n"
        "WHAT I NEED FROM YOU: (a) Where does the 62mm offset come from — a HYTEK construction detail, a code requirement, an installer convention? (b) Is it always 62mm, or does it depend on the plate length, the bolt spec, or the slab type? (c) For longer plates, do you put MORE bolts in the middle (we currently put one at each end only — is that right)? If long plates need a bolt every 600/900/1200mm in the body, tell me the spacing rule."
    ),
    36: (
        "WHAT WE EMIT: Mirror of rule #34 at the end of the plate (length-62).\n\n"
        "WHAT I NEED FROM YOU: Same answer as #34 — once one end is settled, the other follows. ALSO: when the plate is short (e.g. 1600mm), does it still get bolts at both ends (62mm and 1538mm), or just one bolt centered?"
    ),
    38: (
        "WHAT WE EMIT: 89mm bottom plates get the slab-anchor pattern (Web@8 + Bolt@62 each end) ONLY when the gauge (steel thickness) is below 1.0mm. Thicker plates skip the slab anchor ops entirely.\n\n"
        "WHAT DETAILER DOES: HG260044 GF-NLBW-89.075 (gauge 0.75) has Web@8 + Bolt@~50 at start. Single corpus. We have no 89mm B-plate samples at gauge 1.0+ to compare.\n\n"
        "MY HYPOTHESIS: Thicker steel doesn't need the same slab anchorage detail — maybe it uses a different fixing method, or relies on its own stiffness without slab bolts.\n\n"
        "WHAT I NEED FROM YOU: (a) In real production, do thicker (1.0+, 1.15) 89mm plates really skip slab bolts? (b) Or is this just a coincidence in our small sample — actually all 89mm plates get bolts? (c) If they skip slab bolts, what fixing method replaces them, and does the codec need to emit ops for that?"
    ),
    42: (
        "WHAT WE EMIT: Raised B plates (Bh, the rough opening sill above doors at z=elevation+61.5mm) get slab-anchor ops (Web@8 + Bolt@62 at the start) ONLY when the plan is NLBW. LBW raised B plates don't get them.\n\n"
        "WHAT DETAILER DOES: HG260001 PK1 N14/B1 (NLBW raised B at length 1872mm, z=61.5) has BOTH cap notches AND Web@8 + Bolt@62. PK4 L4/B2 (LBW raised B) has only the cap notches — no Web/Bolt.\n\n"
        "MY HYPOTHESIS (uncertain): Maybe NLBW raised B plates serve as a structural collector that ties back to the slab through a strap, and the bolt holes are for that strap. LBW raised B plates have less load to transfer so don't need it. But this is a guess — physically the raised B in both is just a sill above an opening.\n\n"
        "WHAT I NEED FROM YOU: (a) WHY does NLBW raised B get slab anchors but LBW raised B doesn't? Is it really the load path? Is it actually about the OPENING type (door vs window)? Is it about the wall's overall load? (b) Or is this just a pattern quirk in our small corpus and the real rule is different?"
    ),
    43: (
        "WHAT WE EMIT: Mirror of rule #42 at the end of the raised B (length-62).\n\n"
        "WHAT I NEED FROM YOU: Same answer as #42."
    ),
    50: (
        "WHAT WE EMIT: 89mm nogs get the same length-bucketed pattern as 70mm: short-bucket (162-168mm) gets header-style caps; everything else gets Swage caps. The 162-168mm threshold copied from 70mm.\n\n"
        "WHAT I NEED FROM YOU: (a) Confirm the 164mm bucket (door-head cripple block) is the same on 89mm. (b) Confirm the cap pattern is the same (header-style for 164mm, Swage for everything else). (c) If the threshold differs (e.g. 89mm uses 180-188 instead), tell me."
    ),
    54: (
        "WHAT WE EMIT: 70mm full headers get a paired dimple at 58.5mm from the start, but ONLY on LBW plans.\n\n"
        "WHAT I NEED FROM YOU: Same question as #19 — what does the 58.5 dimple represent physically, and why is it LBW-only?"
    ),
    55: (
        "WHAT WE EMIT: Mirror of #54 at the end (length-58.5).\n\n"
        "WHAT I NEED FROM YOU: Same as #54."
    ),
    59: (
        "WHAT WE EMIT: Sticks named H1 or H3 in frames that have a 'paired header' (frame contains H2 or H3 alongside H1) get web stiffener holes evenly distributed along the header body. Spacing: 89mm offset from each end, max 300mm between holes. Verified count = ceil((length - 178) / 300) + 1.\n\n"
        "WHAT DETAILER DOES: HG260001 LBW H1/H3 corpus (10 frames) all match this pattern. Single-H frames (e.g. L4/L8 with just H1, no H2) don't show web stiffener holes.\n\n"
        "MY HYPOTHESIS: A 'paired header' is a built-up box header (two C-sections back-to-back) for wider openings or higher loads. Single-H is a single C-section header for narrower openings. The web stiffener holes are specific to the box-header configuration.\n\n"
        "WHAT I NEED FROM YOU: (a) What physically creates a paired header — span width? Load class? Specific frame type (PK1 vs PK4)? Architectural detail? (b) Are the web stiffeners only on H1/H3, or do H2 also get them? (c) Is the 89mm offset correct, and the 300mm max spacing? Or is it different (e.g. spacing tied to stud spacing)?"
    ),
    60: (
        "WHAT WE EMIT: 89mm headers ALWAYS get the paired 58.5 dimple at both ends — regardless of LBW/NLBW. (70mm headers only get it on LBW.)\n\n"
        "WHAT WORRIES ME: My 89mm header sample is small (HG260012 + a few others) and may all happen to be LBW. The rule might really be 'LBW only' for 89mm too — I just haven't seen 89mm NLBW headers in the data.\n\n"
        "WHAT I NEED FROM YOU: (a) Do 89mm NLBW headers get the paired 58.5 dimple? (b) If they don't, the rule should be 'LBW only' for both 70mm and 89mm. (c) If they do, then 89mm has a different rule and I'd love to know why."
    ),
    61: (
        "WHAT WE EMIT: Wall braces (W in LBW/NLBW plans) get a Chamfer at the start ONLY if the angle from vertical is >= 28 degrees. Near-vertical W's (under 28 deg) don't get a chamfer.\n\n"
        "WHAT DETAILER DOES: HG260001 PK4 L27/W6 at 25.48 deg has NO chamfer. L27/W2 at 29.31 deg HAS a chamfer. So the threshold is somewhere in 25-29 deg.\n\n"
        "MY HYPOTHESIS: The chamfer is needed when the brace meets the plate at a sharp enough angle that the corner would interfere — past ~28 deg the cut becomes geometrically necessary. Below ~28 deg the stick is close enough to vertical that it sits flat against the plate.\n\n"
        "WHAT I NEED FROM YOU: (a) Is 28 deg actually the threshold, or is it different (15? 20? 30? 45?)? (b) Is it really an angle threshold, or is it triggered by something else (the angle of the OPPOSITE end, the brace TYPE, a flag in the XML)? (c) Is the chamfer on both ends or only on the angled end?"
    ),
    64: (
        "WHAT WE EMIT: For wall braces, the END Swage span is angle-dependent. Formula: span = 39 / cos(angle from vertical) + 8 * tan^2(angle). Empirical curve fit, RMSE 0.36mm across 280 W sticks.\n\n"
        "WHAT WORRIES ME: The formula gives the right NUMBERS, but I don't know if it's the right MODEL. The 39/cos(angle) part has a geometric justification (perpendicular cap projected onto angled stick axis grows by 1/cos). The 8*tan^2 part is just a residual fit — no physical interpretation.\n\n"
        "WHAT I NEED FROM YOU: What's the actual rule for the end Swage span on a wall brace? Possibilities: (a) Detailer literally computes span as a function of angle from a HYTEK manual formula. (b) The cap is fixed-perpendicular-width and the angled stick shape just makes the AXIAL projection look angle-dependent. (c) The cap follows the cut line (which is angled at the plate join) so its axial extent depends on the cut geometry. If you can describe physically what the end cap of a wall brace looks like, I can replace my curve fit."
    ),
    66: (
        "WHAT WE EMIT: Mirror of #61 at the end of the brace.\n\n"
        "WHAT I NEED FROM YOU: Same as #61."
    ),
    74: (
        "WHAT WE EMIT: 89mm sills (L role) get a paired dimple at 58.5 from the start (in addition to the 16.5 dimple). 70mm lintels DON'T get the 58.5 dimple — they only have 16.5.\n\n"
        "WHAT WORRIES ME: Same shape as the LBW-paired-dimple question (#19, #54). Why does 89mm L always get it but 70mm L doesn't? Is it really profile-dependent or is it the same LBW-only rule and I just haven't seen 70mm LBW lintels with the paired dimple?\n\n"
        "WHAT I NEED FROM YOU: (a) Do 70mm LBW lintels get the 58.5 paired dimple too? (If yes, the rule should match 70mm headers — LBW gets paired, NLBW doesn't.) (b) Is the 58.5 always exactly that, or does it depend on profile size (35mm web/2 + 23.5 = 58.5; for 89mm web that calculation gives 89/2 + 14 = 58.5 too which is suspicious)?"
    ),
    75: (
        "WHAT WE EMIT: Mirror of #74 at the end (length-58.5).\n\n"
        "WHAT I NEED FROM YOU: Same as #74."
    ),
    79: (
        "WHAT WE EMIT: Sticks named with prefix Br or R get a Swage cap of 41mm at the start (vs 39mm for studs, 42mm for Kb).\n\n"
        "WHAT WORRIES ME: Single sample. Br/R sticks are 'wall braces / ribbons' but use slightly different constants from W (which is 41 too) and S (39). The 41 came from one corpus subset.\n\n"
        "WHAT I NEED FROM YOU: (a) What's the difference between Br, R, and W sticks in HYTEK terminology — physically what each represents? (b) Should Br/R use 41mm cap + 11mm dimple (different from studs), or should they actually use 39mm + 16.5mm like studs (same)?"
    ),
    80: (
        "WHAT WE EMIT: Br/R sticks get an InnerDimple at 11mm (vs 16.5 for studs, 10 for Kb).\n\n"
        "WHAT I NEED FROM YOU: Same as #79 — confirm 11mm or correct. (And tell me if Br/R is actually a meaningful distinction or if it's just a subset of W/S.)"
    ),
    81: (
        "WHAT WE EMIT: Mirror of #79 at the end of the stick.\n\n"
        "WHAT I NEED FROM YOU: Same as #79."
    ),
    82: (
        "WHAT WE EMIT: Mirror of #80 at the end.\n\n"
        "WHAT I NEED FROM YOU: Same as #80."
    ),
    83: (
        "WHAT WE EMIT: Where a stud crosses a top or bottom plate in the frame layout, the plate gets a LipNotch (39mm spanned) + InnerDimple at the stud's x-coordinate. Position is computed from each stick's outline corners (the elevation graphics in the XML).\n\n"
        "WHAT DETAILER DOES: Position is mostly RIGHT (within ~5mm of Detailer). The TOOL TYPE is sometimes wrong on RP plans — Detailer uses InnerNotch where we use LipNotch, or Web where we use neither. We don't have a clean rule for which type fires when.\n\n"
        "WHAT I NEED FROM YOU: At a stud-plate crossing, what tool does Detailer emit on the plate, and what determines which type? Possibilities: (a) always LipNotch on T/B; (b) LipNotch unless the stud is a king-stud (Kb), in which case InnerNotch; (c) plan-type-specific (LBW gets LipNotch, RP gets something else); (d) some other rule. If you can describe 'at a crossing, the plate gets X if Y, otherwise Z', I'll match it."
    ),
    84: (
        "WHAT WE EMIT: Where a nog crosses a stud, the stud gets a LipNotch + InnerDimple at the nog's y-coordinate.\n\n"
        "WHAT DETAILER DOES: Same kind of bleed as #83 — position OK, tool type sometimes drifts.\n\n"
        "WHAT I NEED FROM YOU: At a nog-stud crossing, what tool does Detailer put on the stud, and what determines the type?"
    ),
    85: (
        "WHAT WE EMIT: Where a stud crosses a nog, the nog gets THREE ops: Web hole + LipNotch + InnerDimple at the stud's x-coordinate.\n\n"
        "WHAT DETAILER DOES: Same kind of bleed.\n\n"
        "WHAT I NEED FROM YOU: At a stud-nog crossing, do all three (Web + LipNotch + InnerDimple) always fire, or do some plans/configurations skip one or two?"
    ),
    86: (
        "WHAT WE EMIT: NOTHING. We currently emit no ops at truss panel-points.\n\n"
        "WHAT DETAILER DOES: At every 'panel point' on a truss top chord or bottom chord (where a Web stick projects onto the chord centerline), Detailer emits paired InnerDimples spaced ~51mm apart, plus a 47mm-wide LipNotch perpendicular to the chord. We measured this against HG260002 TN33-1 by projecting Web endpoints onto T2 and matching dimple positions (~41mm before each Web projection, ~51mm gap, ~47mm-wide LipNotch).\n\n"
        "SCALE OF THE GAP: ~7,500 missing ops across the 90 TIN pairs in the corpus — 38 percent of all TIN miss volume. Closing this is worth approximately +13pp on TIN-only parity (taking it from ~65 percent to ~78 percent).\n\n"
        "WHAT I NEED FROM YOU: (a) Are the 51mm spacing and 47mm LipNotch width HYTEK manufacturing constants, or do they depend on something (panel spacing, web-stick angle, profile size)? (b) Is the offset from the Web-stick projection always 41mm before, or does it depend on which side of the panel point you're measuring from? (c) Does Detailer also emit something on the Web stick itself at this junction? (d) Does this pattern apply only to TIN trusses or also to TB2B and FJ?"
    ),
    87: (
        "WHAT WE EMIT: For RP plans, the simplifier rewrites the standard wall-stud caps (Swage 0..39 + ID@16.5) on T/B/N plates to chord-style caps (Chamfer + ID@10). On S studs, it rewrites the standard caps to plate-over-plate notch caps (Swage 56..101 + ID@78.5).\n\n"
        "WHAT DETAILER DOES: HALF the 50-pair RP corpus uses these chord-style caps (matches our simplifier — improves parity by 15+ percentage points). The OTHER HALF uses STUD-STYLE caps on T/B/N plates (LipNotch 56..101 + ID@78.5 + ID@170.5...) — same letter, same plan type, totally different cap regime. When our simplifier fires on those it makes them WORSE (regresses by up to 36pp).\n\n"
        "EXAMPLES: HG260001 GF-RP-70.075 has chord-style T plates (we help). HG260006 GF-RP-70.075 has stud-style T plates (we hurt — 33 percent -> 69 percent if we disable the simplifier). Both are RP, both 70.075, both ground-floor.\n\n"
        "MY HYPOTHESES (uncertain): (a) Edge of panel vs middle of panel — outer rake plates use chord-style, inner span plates use stud-style. (b) Single-bay vs multi-bay — single-bay roofs use chord-style. (c) Frame skew angle — flat frames vs sloped get different caps. (d) An XML attribute we don't read.\n\n"
        "WHAT I NEED FROM YOU: What physically separates an RP frame that gets chord-style caps (Chamfer + single ID@10) from one that gets stud-style caps (LipNotch 56..101 + multiple IDs at 78.5, 170.5, etc)? If you can describe the discriminator, the simplifier becomes correct."
    ),
    89: (
        "WHAT WE EMIT: For TB2B truss frames in -TB2B- plans, the simplifier rewrites cap patterns. Hand-tuned on a single job last week.\n\n"
        "WHAT WORRIES ME: Untested at scale on the 54-pair TB2B corpus.\n\n"
        "WHAT I NEED FROM YOU: I'll baseline TB2B-only as a follow-up; for now, anything you know about TB2B truss tooling that's different from regular truss webs would help."
    ),
    90: (
        "WHAT WE EMIT: For -LIN- plan-type linear-truss frames, the simplifier emits a bolt-hole pattern at every web-chord centerline crossing.\n\n"
        "WHAT WORRIES ME: No corpus check beyond the original 1-job tuning. We don't have many -LIN- pairs in the corpus to validate against.\n\n"
        "WHAT I NEED FROM YOU: (a) What are -LIN- plans for, physically? (b) The bolt-hole pattern at web-chord crossings — what's the spacing rule? (c) Are bolts always at the centerline or offset?"
    ),
    91: (
        "WHAT WE EMIT: For LBW/NLBW wall plans, the simplifier emits InnerService holes (electrical access) on every wall stud above a certain length.\n\n"
        "WHAT DETAILER DOES: BIMODAL behaviour. On small jobs (HG260010, 170 sticks): Detailer emits 8 InnerService ops total; we emit 323 — over-emit by ~40x. On big jobs (HG260045, 89.075 LBW): Detailer emits 73; we emit 55 — under-emit. Net: 2,286 missing + 622 extra across the 9-job test sample.\n\n"
        "MY HYPOTHESIS: Same as #5/#6 — Detailer is reading external services data we don't import. Selective emission based on architectural context (load-bearing zone, opening proximity, header proximity).\n\n"
        "WHAT I NEED FROM YOU: Same as #5/#6 — what tells Detailer WHICH studs need service holes? Once we have that rule, this simplifier becomes correct."
    ),
}

# Each row: (Rule #, Section, Stick role, Profile, When, What we emit, 100%?)
ROWS = [
    # A) Wall studs
    (1, "A", "Wall studs (S, J)", "70mm", "Always", "Start Swage 0..39mm (39mm cap from start)", "Yes"),
    (2, "A", "Wall studs (S, J)", "70mm", "Always", "Start InnerDimple at 16.5mm from start", "Yes"),
    (3, "A", "Wall studs (S, J)", "70mm", "Always", "End Swage [length-39 .. length]", "Yes"),
    (4, "A", "Wall studs (S, J)", "70mm", "Always", "End InnerDimple at length-16.5", "Yes"),
    (5, "A", "Wall studs (S, J)", "70/89mm", "Wall plan AND length>=500", "Service hole at 296mm from start (outlet height)", "No"),
    (6, "A", "Wall studs (S, J)", "70/89mm", "Wall plan AND length>=500", "Service hole at 446mm from start (switch height, paired with 296)", "No"),
    (7, "A", "Wall studs (S, J)", "70/89mm", "framecad-import.ts post-process", "Web access holes evenly distributed in body", "No"),
    (8, "A", "Wall studs (S, J)", "89mm", "Always", "Same 4-op pattern as 70mm (#1-4) at 89mm constants", "No"),

    # B) Cripple / king studs (Kb)
    (9, "B", "Cripple/king studs (Kb)", "70mm", "Kb only", "Chamfer at start ONLY (no end chamfer)", "Yes"),
    (10, "B", "Cripple/king studs (Kb)", "70mm", "Kb only", "Start Swage 0..42mm (42mm cap, mid-wall end)", "Yes"),
    (11, "B", "Cripple/king studs (Kb)", "70mm", "Kb only", "Start InnerDimple at 10mm (NOT 16.5)", "Yes"),
    (12, "B", "Cripple/king studs (Kb)", "70mm", "Kb only, angle-dependent", "End Swage span = 45 / cos(angle from horizontal)", "No"),
    (13, "B", "Cripple/king studs (Kb)", "70mm", "Kb only", "End InnerDimple at length-10", "Yes"),
    (14, "B", "Cripple/king studs (Kb)", "89mm", "Always", "Same Kb pattern as 70mm (#9-13)", "No"),

    # C) Header stud (H matched as cripple)
    (15, "C", "Header stud (H, single)", "70mm", "H not Kb", "End Swage span 43mm", "No"),

    # D) Top plates (T, Tp) — short (<200mm)
    (16, "D", "Short top plate (T<200mm)", "70mm", "Length<200mm", "Start InnerNotch span 39mm", "Yes"),
    (17, "D", "Short top plate (T<200mm)", "70mm", "Length<200mm", "Start LipNotch span 39mm", "Yes"),
    (18, "D", "Short top plate (T<200mm)", "70mm", "Length<200mm", "Start InnerDimple at 16.5", "Yes"),
    (19, "D", "Short top plate (T<200mm)", "70mm", "Length<200mm AND LBW (not NLBW)", "Start InnerDimple at 58.5 (paired)", "No"),
    (20, "D", "Short top plate (T<200mm)", "70mm", "Length<200mm AND LBW (not NLBW)", "End InnerDimple at length-58.5", "No"),
    (21, "D", "Short top plate (T<200mm)", "70mm", "Length<200mm", "End InnerDimple at length-16.5", "Yes"),
    (22, "D", "Short top plate (T<200mm)", "70mm", "Length<200mm", "End InnerNotch span 39mm", "Yes"),
    (23, "D", "Short top plate (T<200mm)", "70mm", "Length<200mm", "End LipNotch span 39mm", "Yes"),

    # E) Top plates (T, Tp) — long (>=200mm)
    (24, "E", "Long top plate (T>=200mm)", "70mm", "Length>=200mm", "Start LipNotch span 39mm", "Yes"),
    (25, "E", "Long top plate (T>=200mm)", "70mm", "Length>=200mm", "Start InnerDimple at 16.5", "Yes"),
    (26, "E", "Long top plate (T>=200mm)", "70mm", "Length>=200mm", "End LipNotch span 39mm", "Yes"),
    (27, "E", "Long top plate (T>=200mm)", "70mm", "Length>=200mm", "End InnerDimple at length-16.5", "Yes"),
    (28, "E", "Long top plate (T>=200mm)", "70mm", "DELIBERATELY NOT EMITTED", "InnerNotch on long T plates", "No"),
    (29, "E", "Long top plate (T>=200mm)", "70mm", "DELIBERATELY NOT EMITTED", "InnerService holes on T plates", "No"),
    (30, "E", "Long top plate (T>=200mm)", "89mm", "Length>=200mm", "Same 4-op pattern as 70mm at 89mm constants", "No"),

    # F) Bottom plates (B, Bp)
    (31, "F", "Bottom plate (B, Bp)", "70mm", "Always", "Start LipNotch span 39mm", "Yes"),
    (32, "F", "Bottom plate (B, Bp)", "70mm", "Primary B (B1 or >=1500mm) AND -GF- AND LBW/NLBW", "Start Web hole at 8mm (slab wiring access)", "No"),
    (33, "F", "Bottom plate (B, Bp)", "70mm", "Always", "Start InnerDimple at 16.5", "Yes"),
    (34, "F", "Bottom plate (B, Bp)", "70mm", "Same gates as #32", "Start Bolt at 62mm (slab anchor)", "No"),
    (35, "F", "Bottom plate (B, Bp)", "70mm", "Always", "End LipNotch span 39mm", "Yes"),
    (36, "F", "Bottom plate (B, Bp)", "70mm", "Same gates as #32", "End Bolt at length-62", "No"),
    (37, "F", "Bottom plate (B, Bp)", "70mm", "Always", "End InnerDimple at length-16.5", "Yes"),
    (38, "F", "Bottom plate (B, Bp)", "89mm", "Same gates as #32 + gauge<1.0", "Start/End Web@8 + Bolts@62 (slab anchor pattern)", "No"),

    # G) Raised bottom plates (Bh)
    (39, "G", "Raised B plate (Bh)", "70mm", "Always", "Start InnerNotch span 39mm", "Yes"),
    (40, "G", "Raised B plate (Bh)", "70mm", "Always", "Start LipNotch span 39mm", "Yes"),
    (41, "G", "Raised B plate (Bh)", "70mm", "Always", "Start InnerDimple at 16.5", "Yes"),
    (42, "G", "Raised B plate (Bh)", "70mm", "NLBW only", "Start Web@8 + Bolt@62 (slab anchor on raised B)", "No"),
    (43, "G", "Raised B plate (Bh)", "70mm", "NLBW only", "End Bolt at length-62", "No"),
    (44, "G", "Raised B plate (Bh)", "70mm", "Always", "End InnerDimple at length-16.5", "Yes"),
    (45, "G", "Raised B plate (Bh)", "70mm", "Always", "End InnerNotch span 39mm", "Yes"),
    (46, "G", "Raised B plate (Bh)", "70mm", "Always", "End LipNotch span 39mm", "Yes"),
    (47, "G", "Raised B plate (Bh)", "89mm", "Always", "Header-style caps both ends, NO Web/Bolt", "Yes"),

    # H) Nogs (N)
    (48, "H", "Nogs (N) — door-head cripple", "70mm", "Length 162-168mm", "InnerNotch + LipNotch caps + Dimple@16.5 BOTH ends", "Yes"),
    (49, "H", "Nogs (N) — all other lengths", "70mm", "Length NOT in 162-168mm", "Swage caps + Dimple@16.5 BOTH ends", "Yes"),
    (50, "H", "Nogs (N)", "89mm", "Always (length-bucketed)", "Same pattern as 70mm with 89mm constants", "No"),

    # I) Headers (H matched as full header)
    (51, "I", "Header (H — full)", "70mm", "Always", "Start InnerNotch span 39mm", "Yes"),
    (52, "I", "Header (H — full)", "70mm", "Always", "Start LipNotch span 39mm", "Yes"),
    (53, "I", "Header (H — full)", "70mm", "Always", "Start InnerDimple at 16.5", "Yes"),
    (54, "I", "Header (H — full)", "70mm", "LBW only", "Start InnerDimple at 58.5 (paired)", "No"),
    (55, "I", "Header (H — full)", "70mm", "LBW only", "End InnerDimple at length-58.5", "No"),
    (56, "I", "Header (H — full)", "70mm", "Always", "End InnerDimple at length-16.5", "Yes"),
    (57, "I", "Header (H — full)", "70mm", "Always", "End InnerNotch span 39mm", "Yes"),
    (58, "I", "Header (H — full)", "70mm", "Always", "End LipNotch span 39mm", "Yes"),
    (59, "I", "Header (H — full)", "70mm", "Stick named H1 or H3 AND frame is paired-header", "Web stiffener holes evenly distributed", "No"),
    (60, "I", "Header (H — full)", "89mm", "Always", "InnerNotch+LipNotch caps + paired dimples 16.5 AND 58.5 always both ends", "No"),

    # J) Wall braces (W on LBW/NLBW plans)
    (61, "J", "Wall brace (W on wall plan)", "70/89mm", "Wall plan AND angle from vertical >= 28 deg", "Chamfer at start (diagonal cut)", "No"),
    (62, "J", "Wall brace (W on wall plan)", "70/89mm", "Wall plan", "Start Swage span 41mm (always 41 regardless of angle)", "Yes"),
    (63, "J", "Wall brace (W on wall plan)", "70/89mm", "Wall plan", "Start InnerDimple at 10mm (NOT 16.5)", "Yes"),
    (64, "J", "Wall brace (W on wall plan)", "70/89mm", "Wall plan, angle-dependent", "End Swage span = 39/cos(angle) + 8*tan^2(angle)", "No"),
    (65, "J", "Wall brace (W on wall plan)", "70/89mm", "Wall plan", "End InnerDimple at length-10", "Yes"),
    (66, "J", "Wall brace (W on wall plan)", "70/89mm", "Wall plan AND angle >= 28 deg", "End Chamfer", "No"),

    # K) Truss / floor-joist webs (W on non-wall plans)
    (67, "K", "Truss/joist web (W non-wall)", "70/89mm", "Non-wall plan", "Start Swage span 39mm", "Yes"),
    (68, "K", "Truss/joist web (W non-wall)", "70/89mm", "Non-wall plan", "Start InnerDimple at 16.5", "Yes"),
    (69, "K", "Truss/joist web (W non-wall)", "70/89mm", "Non-wall plan", "End Swage span 39mm", "Yes"),
    (70, "K", "Truss/joist web (W non-wall)", "70/89mm", "Non-wall plan", "End InnerDimple at length-16.5", "Yes"),

    # L) Lintels & sills (L)
    (71, "L", "Lintel/sill (L)", "70mm", "Always", "Start InnerNotch span 39mm", "Yes"),
    (72, "L", "Lintel/sill (L)", "70mm", "Always", "Start LipNotch span 39mm", "Yes"),
    (73, "L", "Lintel/sill (L)", "70mm", "Always", "Start InnerDimple at 16.5", "Yes"),
    (74, "L", "Lintel/sill (L)", "89mm", "Always", "Start InnerDimple at 58.5 (paired)", "No"),
    (75, "L", "Lintel/sill (L)", "89mm", "Always", "End InnerDimple at length-58.5", "No"),
    (76, "L", "Lintel/sill (L)", "70mm", "Always", "End InnerDimple at length-16.5", "Yes"),
    (77, "L", "Lintel/sill (L)", "70mm", "Always", "End InnerNotch span 39mm", "Yes"),
    (78, "L", "Lintel/sill (L)", "70mm", "Always", "End LipNotch span 39mm", "Yes"),

    # M) Wall braces / ribbons (Br, R) — NOT W
    (79, "M", "Brace/Ribbon (Br, R)", "70mm", "Always", "Start Swage span 41mm", "No"),
    (80, "M", "Brace/Ribbon (Br, R)", "70mm", "Always", "Start InnerDimple at 11mm", "No"),
    (81, "M", "Brace/Ribbon (Br, R)", "70mm", "Always", "End Swage span 41mm", "No"),
    (82, "M", "Brace/Ribbon (Br, R)", "70mm", "Always", "End InnerDimple at length-11", "No"),

    # N) Crossings (frame-context.ts)
    (83, "N", "Crossings: plate over stud", "All", "Stud crosses plate", "Plate gets LipNotch + InnerDimple at every stud's x-coord", "No"),
    (84, "N", "Crossings: stud over nog", "All", "Nog crosses stud", "Stud gets LipNotch + InnerDimple at every nog's y-coord", "No"),
    (85, "N", "Crossings: nog over stud", "All", "Stud crosses nog", "Nog gets Web + LipNotch + InnerDimple at every stud's x-coord", "No"),
    (86, "N", "Crossings: truss panel-points", "All", "Web stick projects onto chord", "NOT EMITTED — paired InnerDimples + 47mm-wide LipNotch at every Web-stick projection", "No"),

    # O) Plan-type post-pass simplifiers
    (87, "O", "Simplifier: simplify-rp.ts", "All", "-RP- plans", "Rewrites T/B/N caps to chord-style (Chamfer+ID@10) + S studs to plate-over-plate notch (Swage 56..101 + ID@78.5)", "No"),
    (88, "O", "Simplifier: simplify-tin-truss.ts", "All", "-TIN- plans", "H-stick LipNotch->Swage substitution gated on InnerNotch absence", "Yes"),
    (89, "O", "Simplifier: simplify-tb2b-truss.ts", "All", "-TB2B- + frame=Truss", "TB2B truss frame cap rewrites", "No"),
    (90, "O", "Simplifier: simplify-linear-truss.ts", "All", "-LIN- plans", "Bolt-hole pattern at every web-chord centerline crossing", "No"),
    (91, "O", "Simplifier: simplify-wall-service.ts", "All", "-LBW-/-NLBW- plans", "InnerService hole emission on wall studs", "No"),
]

wb = Workbook()
ws = wb.active
ws.title = "Codec rules"

HEADERS = [
    "#",
    "Section",
    "Stick role",
    "Profile",
    "When (gate / condition)",
    "What we emit (plain English)",
    "100% sure?",
    "My uncertainty (where I want your input)",
    "Scott's correction (write the right rule here)",
]
ws.append(HEADERS)

font_header = Font(name="Arial", bold=True, color="FFFFFF", size=11)
fill_header = PatternFill("solid", start_color="231F20")
align_header = Alignment(horizontal="center", vertical="center", wrap_text=True)
fill_yes = PatternFill("solid", start_color="C8E6C9")
fill_no = PatternFill("solid", start_color="FFCDD2")
fill_correction = PatternFill("solid", start_color="FFF9C4")
align_wrap = Alignment(vertical="top", wrap_text=True)
align_center = Alignment(horizontal="center", vertical="center")
thin = Side(border_style="thin", color="CCCCCC")
border = Border(left=thin, right=thin, top=thin, bottom=thin)

for cell in ws[1]:
    cell.font = font_header
    cell.fill = fill_header
    cell.alignment = align_header
    cell.border = border

ws.row_dimensions[1].height = 36

for row_idx, row_data in enumerate(ROWS, start=2):
    rule_num = row_data[0]
    long_explanation = LONG.get(rule_num, "")
    full_row = list(row_data) + [long_explanation, ""]  # uncertainty + Scott's correction (blank)
    for col_idx, val in enumerate(full_row, start=1):
        c = ws.cell(row=row_idx, column=col_idx, value=val)
        c.font = Font(name="Arial", size=10)
        c.alignment = align_wrap
        c.border = border
    sure = row_data[6]
    sure_cell = ws.cell(row=row_idx, column=7)
    sure_cell.alignment = align_center
    if sure == "Yes":
        sure_cell.fill = fill_yes
        sure_cell.font = Font(name="Arial", size=10, bold=True, color="2E7D32")
        ws.row_dimensions[row_idx].height = 22
    else:
        sure_cell.fill = fill_no
        sure_cell.font = Font(name="Arial", size=10, bold=True, color="C62828")
        ws.cell(row=row_idx, column=9).fill = fill_correction
        # Tall row to fit the long-form explanation
        # ~ 14pt per line; explanations are typically 8-15 lines
        line_count = long_explanation.count("\n") + max(1, len(long_explanation) // 90)
        ws.row_dimensions[row_idx].height = max(120, min(line_count * 14, 380))

widths = {1: 5, 2: 9, 3: 28, 4: 11, 5: 38, 6: 50, 7: 11, 8: 95, 9: 55}
for col, w in widths.items():
    ws.column_dimensions[get_column_letter(col)].width = w

ws.freeze_panes = "A2"

# Summary sheet
ws2 = wb.create_sheet("Summary")
ws2["A1"] = "Codec rule review"
ws2["A1"].font = Font(name="Arial", bold=True, size=14)

ws2["A3"] = "Total rules listed"
ws2["B3"] = f'=COUNTA(\'Codec rules\'!A2:A{1 + len(ROWS)})'

ws2["A4"] = "100% sure (verified across multiple corpora)"
ws2["B4"] = f'=COUNTIF(\'Codec rules\'!G2:G{1 + len(ROWS)},"Yes")'
ws2["B4"].font = Font(name="Arial", bold=True, color="2E7D32")

ws2["A5"] = "Not 100% (need Scott's input)"
ws2["B5"] = f'=COUNTIF(\'Codec rules\'!G2:G{1 + len(ROWS)},"No")'
ws2["B5"].font = Font(name="Arial", bold=True, color="C62828")

ws2["A7"] = "How to use"
ws2["A7"].font = Font(name="Arial", bold=True, size=12)
ws2["A8"] = "1. Sort by '100% sure?' on the 'Codec rules' sheet to see only the No rows."
ws2["A9"] = "2. For each No row: read the long-form explanation in column H, then write the correct rule in column I (yellow)."
ws2["A10"] = "3. When done, hand it back and Claude updates the codec accordingly."
ws2["A12"] = "Sections key:"
ws2["A12"].font = Font(name="Arial", bold=True)
sections = [
    ("A", "Wall studs (S, J)"),
    ("B", "Cripple/king studs (Kb)"),
    ("C", "Header stud (H matched as cripple)"),
    ("D", "Short top plates T < 200mm (sub-plates above headers)"),
    ("E", "Long top plates T >= 200mm"),
    ("F", "Bottom plates (B, Bp)"),
    ("G", "Raised bottom plates (Bh, sill above openings)"),
    ("H", "Nogs (N) horizontal cross-blocking"),
    ("I", "Headers (H) full headers over openings"),
    ("J", "Wall braces (W on LBW/NLBW)"),
    ("K", "Truss/joist webs (W on non-wall plans)"),
    ("L", "Lintels & sills (L)"),
    ("M", "Brace/Ribbon (Br, R) — NOT W"),
    ("N", "Crossings (frame-context.ts)"),
    ("O", "Plan-type post-pass simplifiers"),
]
for i, (s, desc) in enumerate(sections):
    ws2.cell(row=13 + i, column=1, value=s).font = Font(name="Arial", bold=True)
    ws2.cell(row=13 + i, column=2, value=desc)

ws2.column_dimensions["A"].width = 60
ws2.column_dimensions["B"].width = 60

OUT = r"C:\Users\Scott\CLAUDE CODE\hytek-rfy-codec\docs\rules-review.xlsx"
wb.save(OUT)
print(f"Wrote: {OUT}")
print(f"Rows: {len(ROWS)}")
yes_count = sum(1 for r in ROWS if r[6] == "Yes")
print(f"100% sure: {yes_count} / Not 100%: {len(ROWS) - yes_count}")
